django/week4/portfolio/urls.py
from django.urls import include, path, re_path
from django.contrib import admin

from . import views

#routes to views according to path
urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('resume/', include('resume.urls', namespace='resume')),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),
    path('admin/', admin.site.urls),
]

django/week4/resume/urls.py
from django.urls import include, path

from . import views

app_name = 'resume'

urlpatterns = [
    path('', views.home, name='index'),
]

django/week4/resume/models.py
from django.db import models

# Create your models here.
class Resume(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    
    def get_last_name_first_name(self):
        return "{} {}".format(self.last_name, self.first_name)
    def get_full_name(self):
        return "{} {}".format(self.first_name, self.last_name)
    def get_experience(self):
        return self.experience_set.all()
    def get_education(self):
        return self.education_set.all()

class Experience(models.Model):
    parent_resume = models.ForeignKey('Resume', on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=64, null=False, blank=False)
    location = models.CharField(max_length=255, null=False, blank=False)
    start_date = models.DateField(null=False, blank=False)
    end_date = models.DateField(null=False, blank=False)
    description = models.CharField(max_length=255, null=False, blank=True)

    def __str__(self):
        return "{}{}{}".format(self.title, self.location, self.description)

class Education(models.Model):
    parent_resume = models.ForeignKey('Resume', on_delete=models.CASCADE, default=1)
    institution_name = models.CharField(max_length=128, null=False, blank=False)
    location = models.CharField(max_length=255)
    degree = models.CharField(max_length=128)
    major = models.CharField(max_length=128)
    gpa = models.FloatField(default=0.0)

    def __str__(self):
        return "{}{}{}".format(self.institution_name, self.degree, self.major)

django/week4/portfolio/views.py
from django.shortcuts import render

def home(request):
    """
    Takes the request and renders Home page
    """
    return render(request, 'home.html')

def resume(request):
    """
    Takes the request and renders Resume app
    """
    return render(request, 'resume')

def portfolio(request):
    """
    Takes the request and renders Portfolio page
    """
    return render(request, 'portfolio.html')

def contact(request):
    """
    Takes the request and renders Contact page
    """
    return render(request, 'contact.html')

django/week4/resume/views.py
from django.shortcuts import render
from .models import Resume, Education, Experience

def home(request):
    """
    Renders resume app home page for the webpage portfolio "Andry Bintoro"
    Returns resume.html page
    """
    my_resume = Resume.objects.first()

    context = { 'resume':my_resume, }
    #print(context)
    return render(request, 'resume/resume.html', context)

django/week4/resume/templates/resume/home.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    {% block title %}
      <title>Homepage</title>
    {% endblock %}
  </head>
      <body>
        {% block content %}
        {% endblock %}
      </body>
</html>

django/week4/resume/templates/resume/resume.html
{% extends 'base.html' %}
{% load static %}

  {% block content %}
    <h1>{{ resume.get_full_name }}</h1>
    <p><strong>EXPERIENCE</strong></p>
          {% for experience in resume.get_experience %}
            <ul><b>{{experience.title}}</b> - {{experience.location}}<br /></ul>
            <ul>Description: {{experience.description}}<br /></ul>
            <ul>{{experience.start_date}} - {{experience.end_date}}<br /></ul>
          {% endfor %}

    <p><strong>EDUCATION</strong></p>
          {% for education in resume.get_education %}
            <ul><b>{{education.institution_name}}</b>, {{education.location}}<br /></ul>
            <ul>Degree: {{education.degree}}<br /></ul>
            <ul>Major: {{education.major}}<br /></ul>
            <ul>GPA: {{education.gpa}}<br /></ul>
          {% endfor %}

  {% endblock %}

django/week4/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    {% block title %} {% endblock %}
    <link type="text/css" rel='stylesheet' href="{% static 'css/style.css' %}" />
  </head>
  <body>
      <div class="homepage-banner">
        <nav>
        <a href="{% url 'home' %}">Homepage</a> |
        <a href="{% url 'resume:index' %}">Resume</a> |
        <a href="{% url 'portfolio' %}">Portfolio</a> |
        <a href="{% url 'contact' %}">Contact</a>
        </nav>
      </div>
      {% block content %}
      {% endblock %}
  </body>
</html>

django/week4/templates/contact.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
    <head>
      {% block title %}
        <title>Contact Me</title>
      {% endblock %}
      <meta name="viewport" content="width=device-width"/>
      <meta name="description" content="Contact Me Here"/>
      <meta charset="UTF-8">
      <link type="text/css" rel="stylesheet" href = {% static 'css/style.css' %}>
    </head>
    <body>
      {% block content %}
      <div class="container">
      <form action="action_page.php">

      <label for="fname">First Name</label>
      <input type="text" id="fname" name="firstname" placeholder="Type Your First Name..">

      <label for="lname">Last Name</label>
      <input type="text" id="lname" name="lastname" placeholder="Type Your Last Name..">

      <label for="email">Email</label>
      <input type="text" id="email" name="email" placeholder="Type Your Email Address">

      <label for="country">Country</label>
      <select id="country" name="country">
        <option value="australia">Australia</option>
        <option value="brazil">Brazil</option>
        <option value="canada">Canada</option>
        <option value="south africa">South Africa</option>
        <option value="uk">United Kingdom</option>
        <option value="usa">USA</option>
      </select>

      <label for="subject">Subject</label>
      <textarea id="subject" name="subject" placeholder="Write me a message" style="height:200px"></textarea>
          <input type="submit" value="Submit">
      </form>
      </div>
      {% endblock %}
    </body>
</html>

django/week4/templates/home.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    {% block title %}
      <title>Homepage</title>
    {% endblock %}
  </head>
      <body>
        {% block content %}
          <div class='homepage-banner'>
            <h1>Welcome to my Portfolio</h1>
            <hr>
            <h4>Andry Bintoro</h4>
            <p>MS IT Candidate '18</p>
            <p>University of New Hampshire</p>
          </div>
          <div class='homepage-content'>
            <a class='my-button' href="{% url 'home' %}">My Homepage</a>
          </div>
        {% endblock %}
      </body>
</html>

django/week4/templates/portfolio.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    {% block title %}
    <title>Portfolio</title>
    {% endblock %}

    <meta name="viewport" content="width=device-width"/>
    <meta name="description" content="Portfolio of Andry Bintoro."/>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href = {% static 'css/style.css' %}>
  </head>
    <body>
      {% block content %}
      <div class='portfolio-content'>
        <h1>Portfolio</h1>
        <a href="https://foss.unh.edu/projects/index.php/comp730:MeAndYou_Project"> MeAndYou Project with Professor Jonas </a>
        <img src = {% static 'images/meandyou.png' %} alt="Home Page | MeAndYou" />
        <img src = {% static 'images/Aboutus.png' %} alt="About Us | MeAndYou" />
      </div>
      {% endblock %}
    </body>
</html>